CREATE OR REPLACE PROCEDURE  PERSON_DELETEALL ()
LANGUAGE RPGLE
PARAMETER STYLE SQL
DETERMINISTIC
MODIFIES SQL DATA
CALLED ON NULL INPUT
PROGRAM TYPE MAIN
EXTERNAL NAME  PERDLTALL
SPECIFIC PERDLTALL;
