CREATE OR REPLACE PROCEDURE CONTACT_CREATE_B (
  IN FIRSTNAME VARCHAR(255) CCSID 1208 ,
  IN LASTNAME VARCHAR(255) CCSID 1208 ,
  OUT RESULT CLOB(1M) CCSID 1208
)
LANGUAGE RPGLE
PARAMETER STYLE SQL
DETERMINISTIC
MODIFIES SQL DATA
CALLED ON NULL INPUT
PROGRAM TYPE MAIN
EXTERNAL NAME CONCRTB
SPECIFIC CONCRTB;