CREATE OR REPLACE PROCEDURE CONTACT_GETALL (
  OUT RESULT CLOB(1M) CCSID 1208
)
LANGUAGE RPGLE
PARAMETER STYLE SQL
DETERMINISTIC
MODIFIES SQL DATA
CALLED ON NULL INPUT
PROGRAM TYPE MAIN
EXTERNAL NAME CONGETALL
SPECIFIC CONGETALL;